[role="pagenumrestart"]
[[whatis_chapter]]
== What is the Lightning Network?

Lightning is a smart way to improve upon the bitcoin protocol with additional functionality that increases transaction throughput exponentially and reduces the settlement time to a fraction of a second.
It is a whole different protocol that can be used on top of any proof-of-work time-chain or blockchain such as Bitcoin that supports basic smart contracts.

Early Bitcoin contributer Hal Finney already speculated on the idea of building a second layer payment network:

> "Actually there is a very good reason for Bitcoin-backed banks to exist, issuing their own digital cash currency, redeemable for bitcoins. Bitcoin itself cannot scale to have every single financial transaction in the world be broadcast to everyone and included in the block chain. There needs to be a secondary level of payment systems which is lighter weight and more efficient. Likewise, the time needed for Bitcoin transactions to finalize will be impractical for medium to large value purchases.

> Bitcoin backed banks will solve these problems. They can work like banks did before nationalization of currency. Different banks can have different policies, some more aggressive, some more conservative. Some would be fractional reserve while others may be 100% Bitcoin backed. Interest rates may vary. Cash from some banks may trade at a discount to that from others.

> George Selgin has worked out the theory of competitive free banking in detail, and he argues that such a system would be stable, inflation resistant and self-regulating.

> I believe this will be the ultimate fate of Bitcoin, to be the "high-powered money" that serves as a reserve currency for banks that issue their own digital cash. Most Bitcoin transactions will occur between banks, to settle net transfers. Bitcoin transactions by private individuals will be as rare as... well, as Bitcoin based purchases are today." [1]

With the Lightning Network, users can be their own full reserve Bitcoin-backed bank in a decentralized network of peers.
Or choose to have an "account" at a Bitcoin-backed bank by opening a payment channel.


== Why use the Lightning Network?

A second layer protocol can magnify the amount of transactions possible on the settlement layer, so that the base layer will not be overloaded with transactions as Bitcoin adoption grows in the world. 
Instead small value payments can be instantly transmitted in a Lightning Channel, or a chain of channels through the Lightning Network.
As these channels are not settled on-chain with every transaction, it will become more difficult to differentiate the smaller payments that occured on the channel from each other.
With this move to a higher protocol layer, payments also gain more privacy and fungibility depending on the chosen route.


== How does the Lightning Network work?

Think of a thunderstorm, where electricity is ionizing channels of air to dissipate excess energy and neutralize voltage differences that have been building up during the storm. 
A channel of ionized air forms when the voltage or potential difference is greater than the breakdown voltage (..kV) between the different regions in the cloud. 
As the electric current makes its way through the fractal network of ionized air channels it chooses the path of least resistance to reach its destination, a path is formed between the charged up cloud and the ground of earth below. 
Then a bright flash of light followed by a loud bang occurs as the current dissipated in the path of ionized air channels creates a hot plasma.
The Lightning Network is named after this natural phenomenon, where the voltage differences are channel balances and the current is a stream of bitcoin of which ownership is transmitted through those channels.
When lightning strikes the ground, the potential differences are settled at the cost of dissipating energy and making a loud bang.
In the Lightning Network this happens when payment channels close, the final state of the channel is transmitted to the Bitcoin network with a fee for the miners to include it in the next block.


== How to use the Lightning Network?

Many interoperable implementations are under active development using the BOLT specifications. 
It can be run as a mobile application, a desktop light-client or routing-node.
Someday it could be used under-the-hood in your self-filling refridgerator, an autonomous driving taxi or video streaming service paid by the second!

=== References
[1] Hal Finney, December 30th 2010, (https://bitcointalk.org/index.php?topic=2500.msg34211#msg34211)
