[role="pagenumrestart"]
[[ch01_intro_what_is_the_lightning_network]]
== Introduction

=== What is the Lightning Network?

The Lightning Network is considered to be the payment system for Bitcoin.
It is a second layer protocol on top of Bitcoin that defines rules and contracts which enable the fast, secure, private, trust-less and permission-less transfer of Bitcoin.
Users of the Lightning Network are able to transfer Bitcoin among each other at virtually no cost and in real time.
There is no necessity to wait for block confirmations for payments.
Once a payment arrives, it is final and cannot be reversed.
Like a standard Bitcoin transaction a payment on the Lightning Network can only be refunded by the recipient.
While all Bitcoin transactions are stored in the blockchain where they can be tracked the payments on the Lightning Network are off-chain and offer more privacy than Bitcoin payments.
Due to the used onion routing, which is also used in tor even the nodes that are involved in forwarding the payment from the sender to the recipient do not know for whom they deliver the payment.

=== History of the Lightning Network

// The following is working draft and suggested mail stones in the history of the Lightning Network.

* Satoshis nSequence number
* unidirectional payment channels
* white paper
* Milan meeting and creation of BOLTs
* segwit activation
* passing of integration tests / mainnet launch
* Australia Meeting and BOLT 1.1
* The lightning torch
* today

[[user-stories]]
=== Lightning Network Uses, Users, and Their Stories

As an electronic cash system preserves the 3 important properties of money (medium of exchange, store of value, and unit of account).
The invention of money (and in particular Bitcoin) was primarily made to facilitate trade and enable the exchange of value between people.
However, without the Lightning Network Bitcoin is hard to be used concurrently by millions of people.
Therefore, in order to fully understand the uses of the Lightning Network, we'll examine it from the perspective of people using it.
In particular the use cases will come from previous users of Bitcoin as well as people who have not used Bitcoin before.
Each of the people and their stories, as listed here, illustrates one or more specific use cases.
We'll be seeing them throughout the book:

consumer::
A regular consumer on the Internet or in the offline world who wants to do purchases

content creator / curator::
A person or platform offering content on the web.
They want to install a paywall or get tipped by their fans and consumers.
This could even include music or video streaming on demand paying in real time

gamer::
Similar to the content creator a gamer and live streamer would like to be tipped.
However in gaming (and gambling) the transfer of bitcoin could be part of the game for example to trade items or to wage for bets.

refugee::
Remittance are an important way for refugees to help their loved one in their home country.
Characteristic for remittance is that the payments usually are cross border and relatively small.
However they might happen on a monthly bases as they are just a fraction of the monthly wage.

professional bitcoiner::
A person who wants to earn interest on their bitcoin without the risk of lending them to other people could decide to setup routing nodes on the lightning network.
By providing liquidity to the Lightning Network the routing capacities will be increased offering the chance to earn routing fees on the owned bitcoin.

merchants::
Merchants live of the margin of the sold gods.
They usually pay fees for using point of sales services and several payment methods which take a fraction of the transferred money.
This directly decreases the margin on which merchants operate.
A merchant will be happy to get an additional payment method which is virtually for free to the merchant.

=== Getting Started


==== Choosing a Lightning Network Wallet

* full nodes (c-lightning, eclair, lnd) + remote controls
* phone / desktop wallets  (SPV clients)
* custodial services / wallets?
// Mastering bitcoin also had a section about custodial web wallets. So it might be fair to include them.

==== Quick Start

[[getting_first_bitcoin]]
==== Getting Your First Bitcoin on the Lightning Network


[[sending_receiving]]
==== Sending and Receiving Bitcoin on the Lightning Network
