[role="pagenumrestart"]
[[ch05_set_up_a_lightning_node]]
== Set up your Lightning Network Node
The Lightning Network is specified in the lightning-rfc by the open source community.
The lightning-rfc is also called Basics of Lightning Technology (BOLT) which is a collection of documents (BOLTs) that specify the components needed for the protocol.
There are several teams who implement the BOLTs as software which you can run on your computer or a server.
All those teams also contribute to the BOLTs.
In this chapter you will learn how to set up each of the software packages for each of the Lightning Network implementations.
We presented them in alphabetical order to emphasize that we generally do not prefer or recommend one over the other.
It will depend on your preferences which of the software packages you might want to work with.

=== c-lightning
=== eclair

ACINQ is a French company, Make a product for scalability in Bitcoin.
All products that are eclair have, that deal with LN, follow the specifications, her main products are:

eclair: Eclair is a Scala implementation of the Lightning Network. Has graphical user interface (GUI)  and a JSON API.
eclair-mobile: Eclair Mobile is Bitcoin wallet( Written C Lang ) prepare Lightning Network natively, This software is based upon eclair( writthen in Scala), and follows the Lightning Network standard.

=== lightning network daemon (lnd)
=== Comparing the implementations
