[role="pagenumrestart"]
[[ch06_Maintaining_a_lightning_node]]
== Running and Maintaining a Lightning Network Node

=== Implications of Configurations

=== Backups

==== Static channel backups

=== Security of your machine

==== Hot wallet risk

==== Watchtowers

=== Channel management
In order to participate on the Lightning Network you need to have payment channels on your Lighting networknode.
It might be confusing to decide with whom to open channels and which parameters to set for the specific channel policies.
An obvious strategy might be to open channels with shops where you want to buy products.
But what happens if those shops do only accept large channels which are beyond your funds or do not accept public channels at all?
Also if you are not a consumer but a vendor you want to receive payments on the Lightning Network.
Therefor you need others to open channels with you or you need to open channels and use submarine swaps and rebalancing techniques to provide yourself with the ability to receive payments.
Both techniques will be discussed later in this chapter.

==== Autopilots

==== Rebalancing

==== submarine swaps

==== Fees and Centrality
