[preface]
[[preface]]
== Preface

This book is a collaboration between Andreas M. Antonopoulos, Olaoluwa Osuntokun, and Rene Pickhardt.

=== How to Use This Book

[[intended_audience_sec]]
=== Intended Audience

((("intended audience")))This book is mostly intended for *TBD*.

[[conventinons_used_sec]]
=== Conventions Used in This Book

((("typographical conventions")))The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.

[TIP]
====
This element signifies a tip or suggestion.
====

[NOTE]
====
This element signifies a general note.
====

[WARNING]
====
This element indicates a warning or caution.
====

[[code_examples_sec]]
=== Code Examples

((("code examples, obtaining and using")))The examples are illustrated in Go, C++, Python, and using the command line of a Unix-like operating system. All code snippets are available in the GitHub repository under the _code_ subdirectory. Fork the book code, try the code examples, or submit corrections via GitHub: https://github.com/lnbook/lnbook.

All the code snippets can be replicated on most operating systems with a minimal installation of compilers, interpreters, and libraries for the corresponding languages. Where necessary, we provide basic installation instructions and step-by-step examples of the output of those instructions.

Some of the code snippets and code output have been reformatted for print. In all such cases, the lines have been split by a backslash (+\+) character, followed by a newline character. When transcribing the examples, remove those two characters and join the lines again and you should see identical results to those shown in the example.

All the code snippets use real values and calculations where possible, so that you can build from example to example and see the same results in any code you write to calculate the same values. For example, the private keys and corresponding public keys and addresses are all real.

[[using_code_examples_sec]]
=== Using Code Examples

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you're reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O'Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product's documentation does require permission.

((("attribution")))We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, ISBN, and copyright. For example: &#x201c;__Mastering the Lightning Network__ by Andreas M. Antonopoulos, Olaoluwa Osuntokun, Rene Pickhardt (O'Reilly). Copyright 2020, ISBN - xxx-xx-x-xxxxx."

((("open source licenses")))__Mastering the Lightning Network__ is offered under the Creative Commons Attribution-Noncommercial-No Derivative Works 4.0 International License (CC BY-NC-ND 4.0).

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== References to Companies and Products

All references to companies and products are intended for educational, demonstration, and reference purposes. The authors do not endorse any of the companies or products mentioned. We have not tested the operation or security of any of the products, projects, or code segments shown in this book. Use them at your own risk!

[[addresses_and_transactions_sec]]
=== Addresses and Transactions in this Book

((("blockchain","warnings and cautions")))((("keys and addresses", seealso="cryptography; private keys; public keys")))((("QR codes")))((("transactions","warnings and cautions")))((("warnings and cautions","when using test and example material appearing in book")))The Bitcoin addresses, transactions, keys, QR codes, and blockchain data used in this book are, for the most part, real. That means you can browse the blockchain, look at the transactions offered as examples, retrieve them with your own scripts or programs, etc.

((("warnings and cautions","avoid sending money to addresses appearing in book")))However, note that the private keys used to construct the addresses printed in this book have been "burned." This means that if you send money to any of these addresses, the money will either be lost forever or (more likely) appropriated, since anyone who reads the book can take it using the private keys printed herein.

[WARNING]
====
DO NOT SEND MONEY TO ANY OF THE ADDRESSES IN THIS BOOK. Your money will be taken by another reader, or lost forever.
====

=== O'Reilly

[role = "ormenabled"]
[NOTE]
====
For almost 40 years, pass:[<a href="http://oreilly.com" class="orm:hideurl"><em class="hyperlink">O’Reilly Media</em></a>] has provided technology and business training, knowledge, and insight to help companies succeed.
====

Our unique network of experts and innovators share their knowledge and expertise through books, articles, conferences, and our online learning platform. O’Reilly’s online learning platform gives you on-demand access to live training courses, in-depth learning paths, interactive coding environments, and a vast collection of text and video from O'Reilly and 200+ other publishers. For more information, please visit pass:[<a href="http://oreilly.com" class="orm:hideurl"><em>http://oreilly.com</em></a>].

[[how_to_contact_us_sec]]
=== How to Contact Us

Information about _Mastering the Lightning Network_ as well as the Open Edition and translations are available at link:$$https://lnbook.info/$$[].

((("comments and questions")))((("contact information")))Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

Send comments or technical questions about this book to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

For more information about our books, courses, conferences, and news, see our website at link:$$https://www.oreilly.com$$[].

Find us on Facebook: link:$$https://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$https://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$https://www.youtube.com/oreillymedia$$[]

==== Contacting Andreas

You can contact Andreas M. Antonopoulos on his personal site:
link:$$https://aantonop.com/$$[]

Subscribe to Andreas's channel on YouTube:
link:$$https://www.youtube.com/aantonop$$[]

Like Andreas's page on Facebook:
link:$$https://www.facebook.com/AndreasMAntonopoulos$$[]

Follow Andreas on Twitter:
link:$$https://twitter.com/aantonop$$[]

Connect with Andreas on LinkedIn:
link:$$https://linkedin.com/company/aantonop$$[]

Andreas would also like to thank all of the patrons who support his work through monthly donations. You can support Andreas on Patreon at link:$$https://patreon.com/aantonop$$[].

==== Contacting Rene

You can contact Rene Pickhardt on his personal site:
link:$$https://www.rene-pickhardt.de/$$[]

Subscribe to Rene's channel on YouTube:
link:$$https://www.youtube.com/user/RenePickhardt$$[]

Follow Rene on Twitter:
link:$$https://twitter.com/renepickhardt$$[]

Connect with Rene on LinkedIn:
link:$$https://www.linkedin.com/in/rene-pickhardt-80313744/$$[]

Rene would also like to thank all of the patrons who support his work through monthly donations. You can support Rene on Patreon at link:$$https://patreon.com/renepickhardt$$[].

Or you can support his work directly with bitcoin (also via the Lightning Network) at link:$$https://tallyco.in/s/lnbook$$[] for which Rene is equally thankful as for his patreons.

[[acknowledgments_sec]]
=== Acknowledgments by Andreas

I owe my love of words and books to my mother, Theresa, who raised me in a house with books lining every wall. My mother also bought me my first computer in 1982, despite being a self-described technophobe. My father, Menelaos, a civil engineer who published his first book at 80 years old, was the one who taught me logical and analytical thinking and a love of science and engineering.

Thank you all for supporting me throughout this journey.

=== Acknowledgments by Rene

I want to mainly thank all the students I ever taught and who engaged into interesting discussions and questions.
Believe it or not from you I learnt the most.
I am also grateful to the Bitcoin and Lightning Network community who welcomed me and supported my efforts.
In particular I am grateful to all the open source Bitcoin and Lightning Network protocol developers and people who fund them to make that technology possible.
Last but not least I am thankful to my loved ones.

[[github_contrib]]
=== Contributions

Many contributors offered comments, corrections, and additions to the book as it was collaboratively written on GitHub.

Following is an alphabetically sorted list of all the GitHub contributors, including their GitHub IDs in parentheses:

* 8go (@8go)
* Alpha Q. Smith (@alpha_github_id)
* Brian L. McMichael (@brianmcmichael)
* Darius E. Parvin (@DariusParvin)
* Doru Muntean (@chriton)
* Eduardo Lima III (@elima-iii)
* Emilio Norrmann (@enorrmann)
* Francisco Calderón (@grunch)
* Haoyu Lin (@HAOYUatHZ)
* Hatim Boufnichel (@boufni95)
* Imran Lorgat (@ImranLorgat)
* Julien Wendling (@trigger67)
* Kory Newton (@korynewton)
* Luigi (@gin)
* Patrick Lemke (@PatrickLemke)
* Ricardo Marques (@RicardoM17)
* Sergei Tikhomirov (@s-tikhomirov)
* Simone Bovi (@SimoneBovi)
* Omega X. Last (@omega_github_id)
* Umar Bolatov (@bolatovumar)

Without the help offered by everyone listed above, this book would not have been possible. Your contributions demonstrate the power of open source and open culture, and we are eternally grateful for your help.

Thank you.

=== Sources

This book references various public and open-licensed sources:

https://github.com/lightningnetwork/lightning-rfc/::
Creative Commons Attribution (CC-BY 4.0)
