# alias lightning-cli="lightning-cli --network regtest --lightning-dir=/lightningd"
#
# [[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
#     . /usr/share/bash-completion/bash_completion
